(()=>{
'use strict';
const families=[
{name:'EVOLVING STORIES',tagline:'Scents that change as the story unfolds.',items:[
{name:'THE GIFT OF DEATH / CADoul MORȚII',line:'An ending is not always the end.',notes:'Act I — What Remains: old paper · antique wood · dusty iris · cedar · oak | Act II — The Passing: fine leather · unburnt tobacco · restrained patchouli · warm resin | Act III — What Grows After: black vanilla · honey · fig · blackcurrant · dark florals',story:'An old room after everyone has gone. Books, polished furniture, dust suspended in the light. Slowly, warmth returns. Resin softens into honey, dark fruit appears, and something begins to bloom. The Gift of Death is not a fragrance about dying. It is about what an ending leaves behind — and the strange beauty capable of growing from it.',arc:'OLD → DUST → DECAY → TRANSFORMATION → SWEETNESS → NEW LIFE'},
{name:'THE LAST TRAIN HOME',line:'Some journeys smell different once you know where they end.',notes:'Departure: rain · cold metal · damp air | Journey: worn textile · dry wood · faint coffee | Arrival: warm skin · coffee · soft woods · comforting musk',story:'At first, everything feels foreign: a wet platform, cold rails, rain against the window. Then the carriage warms. Someone opens a coffee. Fabric, wood and skin replace the metallic cold. By the final stop, the fragrance no longer smells like travelling. It smells like coming home.'},
{name:'AFTER THE FUNERAL',line:'Life has the indecency — and the beauty — to continue.',notes:'Beginning: lilies · wet earth · cool air | Middle: quiet incense · old wood | After: crushed green leaves · tender stems · luminous florals',story:'It begins where you expect it to: lilies, damp earth and the last trace of incense. But it refuses to remain there. Green things begin pushing through the soil. Air enters the composition. The flowers change. After the Funeral is grief without permanence — a fragrance about the first almost-guilty moment when the world becomes beautiful again.'},
{name:'3:17 A.M.',line:"For the hour when yesterday has ended but tomorrow hasn't quite begun.",notes:'3:17: cold night air · ozone · clean sheets | 4:42: skin · soft musk · electric air | 6:03: black coffee · pale woods · morning air',story:'The room is silent. The sheets are cold. Somewhere outside, electricity hangs in the air before dawn. Skin slowly warms the bed; eventually coffee replaces ozone. Nothing dramatic happened. And somehow, by morning, everything feels slightly different.'},
{name:'THE HOUSE REMEMBERS',line:'People leave. Rooms keep things.',notes:'old timber · furniture wax · yellowed books · paper dust · dried apple · distant chimney smoke',story:'Open a house that has been closed for years. The furniture still carries its polish. Books have aged on their shelves. Somewhere there is the sweetness of dried apples and the impossible suggestion of smoke from a fire that went out long ago. The House Remembers smells like a place continuing to hold the people who are no longer inside it.'},
{name:'THE WITCH WAS RIGHT',line:'Unfortunately, she did tell you so.',notes:'crushed wild herbs · black tea · blackcurrant · dark berries · resin · burnt honey · faint smoke · dark woods',story:"Green, bitter and suspicious at first. Then fruit appears beneath the herbs, resin warms on the skin and burnt honey turns unexpectedly beautiful. You probably shouldn't have ignored her."},
{name:'THE HOUSE BURNS DOWN',line:'Let beauty come out of ashes.',notes:'Act I — Fire: smoke · charred wood · burnt paper | Act II — After: warm resin · wet earth · rain | Act III — Return: crushed leaves · green stems · new flowers · honey',story:'First comes destruction. Smoke clings to wood and fragments of paper disappear into ash. Then rain arrives. The earth becomes wet. Green stems push through what remains, flowers open, and finally there is honey. The House Burns Down is designed to become more beautiful the longer you wear it.'}
]},
{name:'RELIEF IN TIMES OF DIET',tagline:'Forbidden comfort. Zero calories. Questionable self-control.',items:[
{name:'SUNDAY ROAST',line:'Zero calories. Emotionally, several thousand.',notes:'rosemary · thyme · cracked pepper · browned butter accord · toasted crust · baked potato accord · warm woods',story:'Sunday lunch without washing a single roasting tray. Aromatic herbs and pepper open into browned butter and toasted warmth before settling into the soft, comforting impression of something that absolutely should have come with gravy.'},
{name:'FRENCH BAKERY AT 7 A.M.',line:'Cruelty, but make it Parisian.',notes:'cultured butter · warm pastry dough · toasted croissant crust · espresso · bitter-orange marmalade · vanilla',story:'The exact smell you encounter while dieting and walking past a bakery that has chosen violence.'},
{name:'PIZZA NIGHT',line:'A dangerously comforting idea.',story:'Tomato-red nostalgia, late-night laughter and the promise that one slice was never going to be the plan.'},
{name:'CINNAMON ROLL INCIDENT',line:'It was supposed to be a small one.',story:'Warm, sticky comfort with the unmistakable atmosphere of a decision that escalated beautifully.'},
{name:'MOVIE NIGHT',line:'The film is optional. The snacks are not.',story:'A cozy after-dark scent story made for blankets, bad decisions and saying “one more” to absolutely everything.'},
{name:'BOILED POTATO — THE FORBIDDEN FEAST',line:'Luxury is a matter of perspective.',story:'An absurdly sincere tribute to the humble comfort food that becomes haute cuisine the moment someone tells you not to eat it.'},
{name:'DIET SURVIVAL KIT',line:'For emergencies of a highly specific nature.',story:'A fragrant morale package for the heroic, the hungry and everyone who has ever stared too long at a bakery window.'}
]},
{name:'SERIOUSLY UNSERIOUS™',tagline:'Fine fragrance. Questionable inspiration.',items:[
{name:'EAU DE CHANTIER — CHANTIER INTENSE™',line:'For those who detect notes of concrete and think: luxurious.',notes:'Opening: mineral air · cement dust accord · ozone · warm stone · steel | Heart: sun-warmed salty skin · clean musk · warm cotton · dry cedar | Drydown: fresh-cut timber · resin · black coffee · mineral accord · whisper of hot asphalt',story:'The fragrance nobody requested and, inexplicably, somebody needed. Cold construction materials meet sun-warmed skin, fresh timber and black coffee. Industrial without becoming dirty; strange without becoming unwearable.',arc:'CHANTIER INTENSE™ — Eau de Parfum. Questionable zoning permission.'},
{name:'FRESHLY DIVORCED',line:'Top notes of freedom. Base notes of keeping the good towels.',notes:'chilled champagne · lipstick accord · crisp paper · expensive leather · cold air · clean musk',story:"It opens with champagne because apparently we're celebrating. Lipstick and polished leather follow, while an unnervingly crisp paper accord suggests that somebody has recently signed something important."},
{name:'IKEA RELATIONSHIP TEST',line:'Some accords require assembly.',notes:'Swedish pine · fresh cardboard · pencil shavings · cinnamon bun · coffee · clean wood',story:'Pine and cardboard arrive first. Pencil shavings follow. Coffee and cinnamon attempt mediation. Somewhere around the drydown, one tiny screw is still missing.',arc:'Fine Swedish fury.'},
{name:'MONDAY, UNFORTUNATELY',line:'An eau de parfum with excellent attendance.',notes:'Opening: aggressively black coffee | Heart: warm printer paper · mineral ink/toner accord | Base: clean cotton · office woods · white musk',story:'Coffee arrives before personality. Paper follows. Then the strangely clean smell of an office that has already sent you three emails marked urgent.'},
{name:'SALARY JUST HIT',line:'For approximately seventeen financially irresponsible minutes.',notes:'paper · ink · polished leather · expensive perfume · coffee',story:'Crisp paper, polished leather and the confident trace of expensive perfume meet coffee in that brief, glorious interval when the bank balance looks full of possibility.'},
{name:"GRANDMA'S PLASTIC-COVERED SOFA",line:'Immaculate. Indestructible. Slightly squeaky.',story:'A lovingly absurd monument to the furniture nobody was actually allowed to touch.'},
{name:'THE UBER IS HERE',line:'You said you were ready five minutes ago.',story:'The scent of last-second decisions, one missing shoe and pretending the driver has not been waiting outside.'},
{name:'ONE MORE EPISODE',line:'A fragrance with absolutely no respect for bedtime.',story:'Soft after-dark comfort for the ancient ritual of promising yourself this is definitely the last one.'},
{name:"I CLEANED BECAUSE YOU'RE COMING OVER",line:'Domestic excellence under suspiciously specific circumstances.',story:'The polished, freshly arranged confidence of a home that would like you to believe it always looks like this.'}
]},
{name:'EXPERIMENTAL / ODDITIES',tagline:'For scents that refuse ordinary categories.',items:[
{name:'SHINIMARC™',line:'Clean. Salty. Sweet. Slightly suspicious.',notes:'Opening: sea salt · marine air · ozone · aldehydes | Heart: clean musk · mineral skin | Strange little interruption: an extremely restrained antiseptic accord | Drydown: pale woods · honey · skin musk',story:'Sea air meets immaculate cleanliness, then something oddly clinical flashes through the composition before honey begins warming everything underneath. The medicinal facet is deliberately tiny: enough to make you wonder what you smelled, never enough to make the fragrance smell like a hospital.'}
]}
];
// Preserve the bilingual product title exactly as customer-facing copy.
families[0].items[0].name='THE GIFT OF DEATH / CADOUL MORȚII';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const noteHtml=s=>esc(s).replace(/ \| /g,'<br>');
function render(){const anchor=document.querySelector('#scent-stories');if(!anchor||document.querySelector('#fragrance-world'))return;const section=document.createElement('section');section.id='fragrance-world';section.className='fragrance-world';section.innerHTML=`<p class="section-kicker">Velvet Scent Stories</p><h3>Fragrance World</h3><p class="fragrance-world-intro">Some fragrances begin with a note. Others begin with a place, an hour, a memory, a terrible decision or the strange beauty that appears after everything changes.</p><div class="fragrance-family-grid">${families.map(f=>`<article class="fragrance-family"><h4>${esc(f.name)}</h4><p class="fragrance-tagline">${esc(f.tagline)}</p><div class="fragrance-list">${f.items.map(i=>`<details class="fragrance-story"><summary><strong>${esc(i.name)}</strong><span>${esc(i.line)}</span></summary>${i.notes?`<p class="fragrance-notes">${noteHtml(i.notes)}</p>`:''}<p>${esc(i.story)}</p>${i.arc?`<p class="fragrance-arc">${esc(i.arc)}</p>`:''}</details>`).join('')}</div></article>`).join('')}</div>`;anchor.insertAdjacentElement('afterend',section);}
document.addEventListener('DOMContentLoaded',render);
})();
