/* Native FR/IT/DE localization for Body Glow About page. */
(() => {
  'use strict';
  const maps = {
    fr: {
      'Fourteen artists, one creative home':'Quatorze artistes, un même univers créatif',
      'About Velvet Charms':'À propos de Velvet Charms',
      'Velvet Charms is a collective of 14 artists who work together across different crafts, combining individual skills, imagination and attention to detail in one thoughtful creative studio.':'Velvet Charms est un collectif de 14 artistes réunis autour de savoir-faire différents. Chacun apporte sa technique, son imagination et son sens du détail à un même atelier créatif pensé avec soin.',
      'Our collections bring together ritual candles, artisanal soaps, body care, perfumes, knitted and felted creations, decorative art and personalized commissions. This shared range of skills allows us to create more than a product: we can shape meaningful pieces around a person, a memory, an occasion or an idea.':'Nos collections réunissent bougies rituelles, savons artisanaux, soins du corps, parfums, créations tricotées ou feutrées, objets décoratifs et commandes personnalisées. Cette diversité de savoir-faire nous permet de créer bien plus qu’un produit : des pièces porteuses de sens, imaginées autour d’une personne, d’un souvenir, d’une occasion ou d’une idée.',
      'Meet the collective':'Rencontrez le collectif',
      'Fourteen Makers, Many Creative Worlds':'Quatorze créateurs, de nombreux univers artistiques',
      'Our studio is shaped by fourteen individual perspectives and a shared commitment to thoughtful, high-quality work. Each portrait captures one moment in the studio, while the specialties below reflect the wider creative practice each artist brings to Velvet Charms. Together, we combine materials, techniques and ideas across every collection.':'Notre atelier est façonné par quatorze sensibilités différentes et par une même exigence de qualité. Chaque portrait saisit un instant de vie au studio, tandis que les spécialités présentées ci-dessous reflètent l’univers plus large que chaque artiste apporte à Velvet Charms. Ensemble, nous croisons matières, techniques et idées au fil de toutes nos collections.',
      'Needle-Felted Animals & Keepsakes':'Animaux feutrés à l’aiguille & objets-souvenirs','Botanical Skincare & Body Care':'Soins botaniques du visage & du corps','Knitted & Braided Textile Art':'Art textile tricoté & tressé','Perfumery & Scent Design':'Parfumerie & création olfactive','Bespoke Gifting & Creative Styling':'Cadeaux sur mesure & direction créative','Spiritual & Sculptural Candles':'Bougies spirituelles & sculpturales','Artisan Soapmaking & Botanical Forms':'Savonnerie artisanale & formes botaniques','Knitwear & Winter Accessories':'Maille & accessoires d’hiver','Resin Art & Botanical Décor':'Art en résine & décoration botanique','Clay Sculpture & Figurative Art':'Sculpture en argile & art figuratif','Custom Petwear & Textile Finishing':'Accessoires textiles sur mesure pour animaux','Pet Portraits & Miniature Sculpture':'Portraits d’animaux & sculpture miniature',
      'Artistic portraits representing the people, specialist crafts and creative spirit of our fourteen-person collective.':'Portraits artistiques représentant les personnes, les savoir-faire et l’esprit créatif de notre collectif de quatorze artistes.',
      'Made with purpose':'Créé avec intention','Every creation is made to order or produced in a small batch. We take the time to consider the materials, finishing details and character of each piece rather than treating it as something mass-produced.':'Chaque création est réalisée sur commande ou en petite série. Nous prenons le temps de choisir les matières, de soigner les finitions et de préserver le caractère de chaque pièce, loin d’une logique de production de masse.',
      'Created around your story':'Créé autour de votre histoire','Many pieces can be personalized through color, fragrance, form, message or reference photographs. From subtle adjustments to completely bespoke work, we guide you through the details before production begins.':'De nombreuses pièces peuvent être personnalisées par la couleur, le parfum, la forme, un message ou des photos de référence. D’un ajustement discret à une création entièrement sur mesure, nous vous accompagnons dans les détails avant le début de la fabrication.',
      'Beyond the catalogue':'Au-delà du catalogue','Have Something Different in Mind?':'Vous imaginez autre chose ?','If the creation you are looking for is not currently displayed on our website, tell us about your idea. When it falls within the skills of our artist collective, we will carefully review the request and prepare a separate quotation, together with a realistic production timeframe, before any work begins.':'Si la création que vous recherchez n’apparaît pas encore sur notre site, parlez-nous de votre idée. Lorsqu’elle correspond aux savoir-faire de notre collectif, nous l’étudions avec attention et vous transmettons un devis séparé ainsi qu’un délai de fabrication réaliste avant tout début de travail.','Share your idea':'Partager votre idée',
      'Ordering with care':'Une commande accompagnée avec soin','Payment reserves your place in our production schedule. Within 1–2 business days, we confirm your production window and estimated dispatch date. Intricate or fully personalized commissions receive an individual price and timeframe so that every detail is clear before the creation begins.':'Le paiement réserve votre place dans notre planning de production. Sous 1 à 2 jours ouvrés, nous confirmons votre créneau de fabrication et la date d’expédition estimée. Les commandes complexes ou entièrement personnalisées reçoivent un prix et un délai individualisés afin que chaque détail soit clair avant le début de la création.'
    },
    it: {
      'Fourteen artists, one creative home':'Quattordici artisti, un’unica casa creativa','About Velvet Charms':'Chi è Velvet Charms',
      'Velvet Charms is a collective of 14 artists who work together across different crafts, combining individual skills, imagination and attention to detail in one thoughtful creative studio.':'Velvet Charms è un collettivo di 14 artisti che lavorano in discipline diverse, unendo competenze individuali, immaginazione e attenzione ai dettagli in un unico studio creativo curato con attenzione.',
      'Our collections bring together ritual candles, artisanal soaps, body care, perfumes, knitted and felted creations, decorative art and personalized commissions. This shared range of skills allows us to create more than a product: we can shape meaningful pieces around a person, a memory, an occasion or an idea.':'Le nostre collezioni riuniscono candele rituali, saponi artigianali, cura del corpo, profumi, creazioni lavorate a maglia o infeltrite, arte decorativa e commissioni personalizzate. Questa varietà di competenze ci permette di creare più di un semplice prodotto: possiamo dare forma a pezzi significativi costruiti intorno a una persona, un ricordo, un’occasione o un’idea.',
      'Meet the collective':'Conosci il collettivo','Fourteen Makers, Many Creative Worlds':'Quattordici creatori, molti mondi creativi',
      'Our studio is shaped by fourteen individual perspectives and a shared commitment to thoughtful, high-quality work. Each portrait captures one moment in the studio, while the specialties below reflect the wider creative practice each artist brings to Velvet Charms. Together, we combine materials, techniques and ideas across every collection.':'Il nostro studio nasce da quattordici punti di vista diversi e da un impegno comune verso un lavoro accurato e di qualità. Ogni ritratto racconta un momento nello studio, mentre le specialità qui sotto mostrano la pratica creativa più ampia che ciascun artista porta in Velvet Charms. Insieme uniamo materiali, tecniche e idee in tutte le collezioni.',
      'Needle-Felted Animals & Keepsakes':'Animali infeltriti ad ago & ricordi','Botanical Skincare & Body Care':'Skincare botanica & cura del corpo','Knitted & Braided Textile Art':'Arte tessile lavorata a maglia & intrecciata','Perfumery & Scent Design':'Profumeria & creazione olfattiva','Bespoke Gifting & Creative Styling':'Regali su misura & styling creativo','Spiritual & Sculptural Candles':'Candele spirituali & scultoree','Artisan Soapmaking & Botanical Forms':'Saponificazione artigianale & forme botaniche','Knitwear & Winter Accessories':'Maglieria & accessori invernali','Resin Art & Botanical Décor':'Arte in resina & decorazioni botaniche','Clay Sculpture & Figurative Art':'Scultura in argilla & arte figurativa','Custom Petwear & Textile Finishing':'Accessori tessili su misura per animali','Pet Portraits & Miniature Sculpture':'Ritratti di animali & scultura in miniatura',
      'Artistic portraits representing the people, specialist crafts and creative spirit of our fourteen-person collective.':'Ritratti artistici che rappresentano le persone, i mestieri specializzati e lo spirito creativo del nostro collettivo di quattordici artisti.',
      'Made with purpose':'Creato con intenzione','Every creation is made to order or produced in a small batch. We take the time to consider the materials, finishing details and character of each piece rather than treating it as something mass-produced.':'Ogni creazione viene realizzata su ordinazione o in piccole serie. Dedichiamo tempo alla scelta dei materiali, alle finiture e al carattere di ogni pezzo, invece di trattarlo come un prodotto di massa.',
      'Created around your story':'Creato intorno alla tua storia','Many pieces can be personalized through color, fragrance, form, message or reference photographs. From subtle adjustments to completely bespoke work, we guide you through the details before production begins.':'Molti pezzi possono essere personalizzati attraverso colore, profumo, forma, messaggio o fotografie di riferimento. Da piccoli adattamenti a lavori completamente su misura, ti accompagniamo nella definizione dei dettagli prima dell’inizio della produzione.',
      'Beyond the catalogue':'Oltre il catalogo','Have Something Different in Mind?':'Hai in mente qualcosa di diverso?','If the creation you are looking for is not currently displayed on our website, tell us about your idea. When it falls within the skills of our artist collective, we will carefully review the request and prepare a separate quotation, together with a realistic production timeframe, before any work begins.':'Se la creazione che cerchi non è ancora presente sul sito, raccontaci la tua idea. Se rientra nelle competenze del nostro collettivo, valuteremo con attenzione la richiesta e prepareremo un preventivo separato insieme a una tempistica di produzione realistica prima di iniziare il lavoro.','Share your idea':'Raccontaci la tua idea',
      'Ordering with care':'Un ordine seguito con cura','Payment reserves your place in our production schedule. Within 1–2 business days, we confirm your production window and estimated dispatch date. Intricate or fully personalized commissions receive an individual price and timeframe so that every detail is clear before the creation begins.':'Il pagamento riserva il tuo posto nel nostro programma di produzione. Entro 1–2 giorni lavorativi confermiamo il periodo di lavorazione e la data di spedizione stimata. Le commissioni più complesse o completamente personalizzate ricevono un prezzo e una tempistica individuali, così ogni dettaglio è chiaro prima di iniziare.'
    },
    de: {
      'Fourteen artists, one creative home':'Vierzehn Künstler, ein kreatives Zuhause','About Velvet Charms':'Über Velvet Charms',
      'Velvet Charms is a collective of 14 artists who work together across different crafts, combining individual skills, imagination and attention to detail in one thoughtful creative studio.':'Velvet Charms ist ein Kollektiv aus 14 Künstlerinnen und Künstlern, die in unterschiedlichen Handwerken arbeiten und ihre individuellen Fähigkeiten, ihre Vorstellungskraft und ihren Blick fürs Detail in einem gemeinsamen Kreativstudio verbinden.',
      'Our collections bring together ritual candles, artisanal soaps, body care, perfumes, knitted and felted creations, decorative art and personalized commissions. This shared range of skills allows us to create more than a product: we can shape meaningful pieces around a person, a memory, an occasion or an idea.':'Unsere Kollektionen vereinen Ritualkerzen, handgemachte Seifen, Körperpflege, Parfums, gestrickte und gefilzte Kreationen, dekorative Kunst und individuelle Auftragsarbeiten. Diese Vielfalt an Fähigkeiten ermöglicht uns, mehr als nur Produkte zu schaffen: persönliche Stücke, die sich um einen Menschen, eine Erinnerung, einen Anlass oder eine Idee formen.',
      'Meet the collective':'Das Kollektiv kennenlernen','Fourteen Makers, Many Creative Worlds':'Vierzehn Kreative, viele künstlerische Welten',
      'Our studio is shaped by fourteen individual perspectives and a shared commitment to thoughtful, high-quality work. Each portrait captures one moment in the studio, while the specialties below reflect the wider creative practice each artist brings to Velvet Charms. Together, we combine materials, techniques and ideas across every collection.':'Unser Studio wird von vierzehn individuellen Perspektiven und einem gemeinsamen Anspruch an sorgfältige, hochwertige Arbeit geprägt. Jedes Porträt hält einen Moment im Atelier fest; die darunter genannten Schwerpunkte zeigen zugleich das breitere kreative Spektrum, das jede Person zu Velvet Charms beiträgt. Gemeinsam verbinden wir Materialien, Techniken und Ideen über alle Kollektionen hinweg.',
      'Needle-Felted Animals & Keepsakes':'Nadelgefilzte Tiere & Erinnerungsstücke','Botanical Skincare & Body Care':'Botanische Haut- & Körperpflege','Knitted & Braided Textile Art':'Gestrickte & geflochtene Textilkunst','Perfumery & Scent Design':'Parfümerie & Duftgestaltung','Bespoke Gifting & Creative Styling':'Individuelle Geschenke & kreatives Styling','Spiritual & Sculptural Candles':'Spirituelle & skulpturale Kerzen','Artisan Soapmaking & Botanical Forms':'Handgemachte Seifen & botanische Formen','Knitwear & Winter Accessories':'Strickwaren & Winteraccessoires','Resin Art & Botanical Décor':'Harzkunst & botanische Dekoration','Clay Sculpture & Figurative Art':'Tonskulptur & figurative Kunst','Custom Petwear & Textile Finishing':'Individuelle Tieraccessoires & Textilveredelung','Pet Portraits & Miniature Sculpture':'Tierporträts & Miniaturskulptur',
      'Artistic portraits representing the people, specialist crafts and creative spirit of our fourteen-person collective.':'Künstlerische Porträts der Menschen, spezialisierten Handwerke und des kreativen Geistes unseres vierzehnköpfigen Kollektivs.',
      'Made with purpose':'Mit Bedeutung geschaffen','Every creation is made to order or produced in a small batch. We take the time to consider the materials, finishing details and character of each piece rather than treating it as something mass-produced.':'Jede Kreation wird auf Bestellung oder in kleiner Serie gefertigt. Wir nehmen uns Zeit für Materialien, Verarbeitung und den eigenen Charakter jedes Stücks, statt es wie ein Massenprodukt zu behandeln.',
      'Created around your story':'Für Ihre Geschichte geschaffen','Many pieces can be personalized through color, fragrance, form, message or reference photographs. From subtle adjustments to completely bespoke work, we guide you through the details before production begins.':'Viele Stücke lassen sich über Farbe, Duft, Form, Botschaft oder Referenzfotos personalisieren. Von kleinen Anpassungen bis zu vollständig individuellen Arbeiten begleiten wir Sie bei den Details, bevor die Fertigung beginnt.',
      'Beyond the catalogue':'Über den Katalog hinaus','Have Something Different in Mind?':'Sie haben etwas anderes im Sinn?','If the creation you are looking for is not currently displayed on our website, tell us about your idea. When it falls within the skills of our artist collective, we will carefully review the request and prepare a separate quotation, together with a realistic production timeframe, before any work begins.':'Wenn die gewünschte Kreation derzeit nicht auf unserer Website zu sehen ist, erzählen Sie uns von Ihrer Idee. Passt sie zu den Fähigkeiten unseres Kollektivs, prüfen wir die Anfrage sorgfältig und erstellen vor Arbeitsbeginn ein separates Angebot mit einem realistischen Fertigungszeitraum.','Share your idea':'Erzählen Sie uns von Ihrer Idee',
      'Ordering with care':'Mit Sorgfalt bestellt','Payment reserves your place in our production schedule. Within 1–2 business days, we confirm your production window and estimated dispatch date. Intricate or fully personalized commissions receive an individual price and timeframe so that every detail is clear before the creation begins.':'Die Zahlung reserviert Ihren Platz in unserer Produktionsplanung. Innerhalb von 1–2 Werktagen bestätigen wir Ihr Fertigungsfenster und das voraussichtliche Versanddatum. Aufwendige oder vollständig personalisierte Aufträge erhalten einen individuellen Preis und Zeitrahmen, damit vor Beginn jedes Detail geklärt ist.'
    }
  };
  const original = new WeakMap();
  const norm = v => String(v || '').replace(/\s+/g, ' ').trim();
  const lang = () => window.VELVET_GET_LANGUAGE?.() || document.documentElement.lang || 'en';
  function restore(){const root=document.querySelector('.about-panel');if(!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);while(w.nextNode()){const n=w.currentNode;if(original.has(n))n.nodeValue=original.get(n);}}
  function apply(){const l=lang();if(!['fr','it','de'].includes(l))return;const root=document.querySelector('.about-panel');if(!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);while(w.nextNode()){const n=w.currentNode;if(!norm(n.nodeValue))continue;if(!original.has(n))original.set(n,n.nodeValue);const src=original.get(n),tr=maps[l]?.[norm(src)];if(tr){const a=src.match(/^\s*/)?.[0]||'',b=src.match(/\s*$/)?.[0]||'';n.nodeValue=a+tr+b;}}}
  function refresh(){restore();apply();}
  window.addEventListener('velvet-language-changed',refresh);document.addEventListener('velvet:language-change',refresh);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(refresh,0),{once:true});else refresh();
})();